import helione from "../../Img/heligrid1.png";
import helitwo from "../../Img/heligrid2.png";
export default [
  {
    id: 1,
    img: helione,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 2,
    img: helitwo,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 3,
    img: helione,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 4,
    img: helitwo,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 5,
    img: helione,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 6,
    img: helitwo,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 7,
    img: helitwo,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 8,
    img: helione,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 9,
    img: helitwo,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
];
