import Everest from "../../Img/Everest.png";
export default [
  {
    id: 1,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 2,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 3,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 4,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 5,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 6,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 7,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 8,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 9,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 10,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 11,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
  {
    id: 12,
    img: Everest,
    name: "Everest Circuit Trek",
    price: "120",
    info: "trek to the top of the world",
    time: "15",
  },
];
